app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

security_check:
    pattern: /admin/check_path

security_login:
    pattern: /login

security_logout:
    pattern: /logout